pipeline {
    agent any
    stages {
        stage('Clean Workspace') {
            steps{
                 sh "rm -rf *"
            }
        }
        stage('Chekout Git') { 
            steps {
                 git branch:'damos_ayobo',
                 url: 'https://github.com/asmakehila1/devops_netcom.git'
                 sh 'echo $WORKSPACE'
            }
        }
        stage('Change Dir'){
            steps{
                sh 'cp -a ./tpAchatProject/. .'
                sh 'rm -rf ./tpAchatProject'
                // List the final content
                sh 'ls -la'
            }
        }
        stage('MVN Clean') { 
            steps {
                 sh 'mvn clean'
            }
        }
        stage('MVN Compile') { 
            steps {
                 sh 'mvn compile'
            }
        }	
        stage("Unit tests") {
			steps {
				sh 'mvn test'
			}
		}
		stage("Static tests") {
			steps {
				sh "mvn sonar:sonar \
  					-Dsonar.projectKey=projet-devops \
					-Dsonar.host.url=http://172.20.2.128:9000 \
  					-Dsonar.login=076c3638275bb6a06907205a9c8e017b04a79f79 "
			}
		}	
		stage('Build docker image'){
            steps{
                script{
                    sh 'docker build -t damosayb/achat .'
                }
            }
        }

	}
}