pipeline {
   agent any

   stages {
       steps{
                dir("${env.WORKSPACE}/tpAchatProjet"){
                    sh "pwd"
                    sh 'mvn clean'
                }
            }
   }

}